# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d5c948ef24b2584fb337f41973451310fe0a9b5c4ea57ee363322df45ba9f93559969a55548a6fad6ae99018c8fb43644cab9ba2d8415e6573bdb45a033a93

test:
  secret_key_base: 09ecf2b2e2fb6bd6b5b745d493e8140333ae34d69ffc5962fa4a43d4f9fef2e7897806296343d04778feaf7f042bdf9bc6ea0fda2edbca802d03411248675953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
